#!/bin/bash
# run
KMOD=3_kprobe
USE_VI=1

[ ${USE_VI} -eq 1 ] && {
  sudo dmesg -C && make && ./test.sh && sleep .1
  vi /0setup*
  sudo rmmod ${KMOD} 2>/dev/null && sudo dmesg
} || {
  echo "sudo dmesg -C && make && ./test.sh && sleep 1 && sudo rmmod ${KMOD} 2>/dev/null && sudo dmesg"
  sudo dmesg -C && make && ./test.sh && sleep 1 && sudo rmmod ${KMOD} 2>/dev/null && sudo dmesg
}
