#!/bin/bash
# load_testmod
# Simple bash wrapper to setup our custom testcases for KASAN & UBSAN

# TODO
# locate_kernel_config()
name=$(basename $0)

setup_testmod()
{
KMOD=test_kmembugs
make || return
[ ! -f ${KMOD}.ko ] && {
   echo "Module ${KMOD}.ko not built? aborting..."
   exit 1
}
sudo rmmod ${KMOD} 2>/dev/null
sudo dmesg -C
sudo insmod ./${KMOD}.ko use_kasan_multishot=${1}
sudo dmesg
}


#--- 'main' here

echo "Kernel ver: $(uname -r)"
ubsan=1
kasan=1
KCONF=/boot/config-$(uname -r)
if ! grep -q "CONFIG_UBSAN=y" ${KCONF}; then
   echo "UBSAN disabled for this kernel"
   ubsan=0
else
   echo "UBSAN enabled"
fi
if ! grep -q "CONFIG_KASAN_GENERIC=y" ${KCONF}; then
   echo "Generic KASAN disabled for this kernel"
   kasan=0
else
   echo "Generic KASAN enabled"
fi
[[ ${ubsan} -eq 0 ]] && [[ ${kasan} -eq 0 ]] && {
   echo "=== NOTE! Both KASAN and UBSAN are disabled for this kernel ==="
}
val=0
[ ${kasan} -eq 1 ] && val=1
setup_testmod ${val}
exit 0
