#!/bin/bash
# run_tests
# Simple bash wrapper to run our custom testcases for KASAN & UBSAN

# TODO
# locate_kernel_config()
name=$(basename $0)
KMOD=test_kmembugs
DBGFS_MNT=/sys/kernel/debug

run_testcases()
{
true

}



#--- 'main' here

if ! lsmod | grep -q ${KMOD} ; then
   echo "${name}: load the test module first by running the load_testmod script"
   exit 1
fi

[ $(id -u) -ne 0 ] && {
	echo "${name}: needs root."
	exit 1
}

#--- verify debugfs pseudo-file is present
[ ! -d ${DBGFS_MNT} ] && {
	echo "${name}: debugfs mount point \"${DBGFS_MNT}\" not present?
If this is expected, pl fix this script to have the correct location and retry"
	exit 1
}
KMOD_DBGFS_FILE=${DBGFS_MNT}/${KMOD}/lkd_dbgfs_run_testcase
[ ! -f ${KMOD_DBGFS_FILE} ] && {
	echo "${name}: debugfs file \"${KMOD_DBGFS_FILE}\" not present? Aborting..."
	exit 1
}

#--- all ok, let's go
echo "Select testcase to run:
1. UMR
2. UAR

Memory leakage
3.1 simple memory leakage testcase1
3.2 simple memory leakage testcase2 - caller to free memory

OOB accesses on static (compile-time) global memory
4.1 

(Type in the testcase number): "
read testcase

# validate

echo "Running testcase \"${testcase}\" via test module now..."
dmesg -C
echo "${testcase}" > ${KMOD_DBGFS_FILE}
dmesg

exit 0
